name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug file structure
        run: ls -R
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # working-directory: lab3/app_python
        run: |
          cd app_python
          pip install -r requirements.txt

      - name: Run linter (flake8)
        # working-directory: lab3/app_python
        run: |
          cd app_python
          ls
          
          flake8 . --count --show-source --statistics || true
      - name: Start Flask App
        run: |
          cd app_python
          python app.py &  # Run in background
          sleep 5  # Wait for the server to start


      - name: Run tests
        # working-directory: lab3/app_python
        run: |
          cd app_python
          pytest -v tests/
      - name: Snyk Python Scan
        uses: snyk/actions/python-3.9@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # From GitHub Secrets
        with:
          command: test
          args: --severity-threshold=high  # Fail on high-severity issues


  docker-publish:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: app_python  # Path to Dockerfile location
          push: true
          tags: yehiasobeh/moscow-time-app:latest
